language: cpp
sudo: required
cache: ccache
services:
  - docker
env:
  global:
    - secure: MsrmyvcB0YGXt3MHdLGlM/IZy6cMHJDN4sfZVKwLchF2/cgvsxvN/ZU4cfksek2y/mgHXS/NlrorZCJBGS2oTrr6sH9/n9eT2enVNlRjoCd5FwNYTHs9L9M6LQH9mtH8n/fdgXKJZ9a3kmoPKY1amX9TKzPTk4LxDNQN1u4b7HBYukGCVmf2tAcAfGbN+wthM/f5hkGIpsOYwchtDApLwA/ps69p7udyGR/brpud9DpeADk1Tt6WfPOX+TvDgR6G7e3y09ZQOZ4yxRVlV1daF9i8gAcfaPewRGRwXNt5QVVVLOWRIsp23KKlUO3ixRTpM1Ze/d//vh1l5MK9rDij0JqNCGX/CO/HEtur+qIgrUCJqBTzF7xQNaiJcLi+NUtxL4s2Jg2MYVrO3SUl1PKFz2MmuONGNL+Bla7u+W56wPIsCesHTa8yWFyJfmEUSDs/QjMoCapxNRujrzjjMjQGaOJwP9RfJKkIxhTo7oUaerLRRddPZbxERFWaQVXmN7SSrmI05HR1I+1VsPyykdcIm4uxochwiKGEKf7D3a4BlngPH/kxmTqXZGlHrLMCHOexFb2TZpY6TsnTTp1kIFAKt7QHtoKj63cJ4yElTyi9n0/muGM34DSAk6pIskdabC6TGOsk+0oFQMIJZ144MsKQhtrRQeuXupvoeSNfTvPV9CA=
    - secure: Zq0nqwwRZa/KLlwz7ggfGzUcsNUBWNFTXP/9KXNhwa003SdDATHM6WEqgPvpBVyd12JzB5xzoIV+MzRVlA45pV2mT7Jdq51BQCCtWdJhA63/kVNl89NN+tFGPh+/dHur0KPFcov0VrC9MVdhDbrqbOr+dYfwiLbVOyk05kYe5QBhEkRBbenx0w8QS1mqum/ak3iDBw89eIUslhcuX49Lxmyw9r7CW29Lkm3mgdaroJyqwvcEH4Pw8nlrLbxF1XRVBuRFYPCPfjt7J5Bi4Onj4NAOu3fhEgpxFc0x4JtpLCbpTUe6W6Aw7Hb378mLFEBob5CsTI+/w3TevA+BKzZ+a/x2Z5sm/crhK2NJDWRY4tPkfBm9PcFTTt/CqGyda4QvbPR3CP0OjdSIwG9MjfBlLnl+FroYuEqzkQO+JHeNfs3PWseu70AxWzGeKcY3eFMijE6wPRzk+6+fl077wHKTKo3NfxGNQDESWeI0q8wD5FYY4fskUkD1pgZ32F8AIM+4h0yplGkfApcz9Oi+NegHFR5E+S7KFtoCBIeusyjfYArw/XMf8d+8XlYBe1x6Mzd3AxBpzZ020P08vI59Kwz+ICARpsw4k6HeDk4QF/hpOC/CsmPpt9zomYNnkvqk6Ia6qfTbVkpH2t42XVGSvHvlI8IOhlj0RukH7eucosGR6oI=

before_install:
  - echo "Testing CI system..."
  - (cd ci; bats tests/*)
  - (cd ci/build; bats tests/*)
  - echo "Registering QEMU with Travis..."
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - ci/install_googletest.sh
  - ci/prebuild.sh /opt/rpi-micromanager
script:
  - make && make test
  - echo "Building the device adapter libraries..."
  - cd $TRAVIS_BUILD_DIR/ci/build
  - docker-compose pull
  - docker-compose up
  - echo "Running unit tests on the app script..."
  - cd $TRAVIS_BUILD_DIR
  - docker build -f ci/app-tester/Dockerfile -t kmdouglass/rpi-micromanager:app-tester .
  - docker run -it --rm kmdouglass/rpi-micromanager:app-tester
before_deploy:
  - VERSION=$(grep -o "\([0-9]\+\.[0-9]\+\.[0-9]\+\)" tacpho/adapters/_version.py)
  - (cd /opt/rpi-micromanager/build/lib/micro-manager; zip -r RPi-DeviceAdapters-$VERSION.zip *)
deploy:
  - provider: script
    script: (cd $TRAVIS_BUILD_DIR/ci/app; make build push)
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: jYltGV0orWRf8Ij3VbwU/fIam2Jj9EEUP9tuOjq0bJs/9D0+zY38JOmuWFpeoM20SuZ9V0/DbjTNjzAiiu/uVQAgmY61pN7HPiJCUR6NwkfF28/plVGJ3FGQADUWs3nprLLrWow90vPOFIGnVxdK7XgBsBF+hBcu7hxNHtFJYL7CYfLbKG18IWqfhAY9jUZRvEKNvQPail9MG34HnsBu7nvk9rXqmkXTeGICQCcLQ3Bm7cx+uaYOT/BiYMeCZui9PGz7pys1gwFt2hrgJVx6riQXJaELfr0bGbiOg6hxND/70bF8rIMG//ZD/2z8WyVPYyC+DEeWzh/4K706wovKKwaYMn+2d4PQpqSsZYKv25XascWx3cjCWPlh5f+5xTb7tdJn332IfTuYJx7xUYu0j3DdA1d0UtEcRiIBN77w4a4pByZC63cioOtW+XQxSTZMjVMOYm/Knrh3+dbdG9B4Meoa/X7XGq2XOFp3p+BOLmRGJR/ggOLrGgRz95OuOKhiRgO7Mo2jbDMVeBGn7baLojyNFfNlJP3HrV9NUZdc18VGV/gLFnJ2P4jZyyaeB6tKQjDheb05lu6HBhwUGsRgfCXYinNbshqEaejwVdjnoAGBVyY0T6UFR0cnWNHn2B2a0RX0u6jZofmJg40EtehG1LWX3+dcofgMYDfUICTjiDM=
    file_glob: true
    file:
      - /opt/rpi-micromanager/build/lib/micro-manager/RPi-DeviceAdapters-*.zip
    on:
      repo: kmdouglass/RPi-DeviceAdapters
      tags: true
